rm incomes/update.php; mv incomes/update.php.new incomes/update.php
rm incomes/view.php; mv incomes/view.php.new incomes/view.php
rm incomes/admin.php; mv incomes/admin.php.new incomes/admin.php
rm incomes/index.php; mv incomes/index.php.new incomes/index.php
rm incomes/create.php; mv incomes/create.php.new incomes/create.php
rm site/contact.php; mv site/contact.php.new site/contact.php
rm site/pages/about.php; mv site/pages/about.php.new site/pages/about.php
rm site/login.php; mv site/login.php.new site/login.php
rm site/index.php; mv site/index.php.new site/index.php
rm pollCodes/update.php; mv pollCodes/update.php.new pollCodes/update.php
rm pollCodes/view.php; mv pollCodes/view.php.new pollCodes/view.php
rm pollCodes/admin.php; mv pollCodes/admin.php.new pollCodes/admin.php
rm pollCodes/index.php; mv pollCodes/index.php.new pollCodes/index.php
rm pollCodes/create.php; mv pollCodes/create.php.new pollCodes/create.php
rm ticketCodes/update.php; mv ticketCodes/update.php.new ticketCodes/update.php
rm ticketCodes/view.php; mv ticketCodes/view.php.new ticketCodes/view.php
rm ticketCodes/admin.php; mv ticketCodes/admin.php.new ticketCodes/admin.php
rm ticketCodes/index.php; mv ticketCodes/index.php.new ticketCodes/index.php
rm ticketCodes/create.php; mv ticketCodes/create.php.new ticketCodes/create.php
rm sites/update.php; mv sites/update.php.new sites/update.php
rm sites/view.php; mv sites/view.php.new sites/view.php
rm sites/admin.php; mv sites/admin.php.new sites/admin.php
rm sites/index.php; mv sites/index.php.new sites/index.php
rm sites/create.php; mv sites/create.php.new sites/create.php
rm bankCodes/update.php; mv bankCodes/update.php.new bankCodes/update.php
rm bankCodes/view.php; mv bankCodes/view.php.new bankCodes/view.php
rm bankCodes/admin.php; mv bankCodes/admin.php.new bankCodes/admin.php
rm bankCodes/index.php; mv bankCodes/index.php.new bankCodes/index.php
rm bankCodes/create.php; mv bankCodes/create.php.new bankCodes/create.php
rm commentCodes/update.php; mv commentCodes/update.php.new commentCodes/update.php
rm commentCodes/view.php; mv commentCodes/view.php.new commentCodes/view.php
rm commentCodes/admin.php; mv commentCodes/admin.php.new commentCodes/admin.php
rm commentCodes/index.php; mv commentCodes/index.php.new commentCodes/index.php
rm commentCodes/create.php; mv commentCodes/create.php.new commentCodes/create.php
rm buildings/update.php; mv buildings/update.php.new buildings/update.php
rm buildings/view.php; mv buildings/view.php.new buildings/view.php
rm buildings/admin.php; mv buildings/admin.php.new buildings/admin.php
rm buildings/index.php; mv buildings/index.php.new buildings/index.php
rm buildings/create.php; mv buildings/create.php.new buildings/create.php
rm ticketHistory/update.php; mv ticketHistory/update.php.new ticketHistory/update.php
rm ticketHistory/view.php; mv ticketHistory/view.php.new ticketHistory/view.php
rm ticketHistory/admin.php; mv ticketHistory/admin.php.new ticketHistory/admin.php
rm ticketHistory/index.php; mv ticketHistory/index.php.new ticketHistory/index.php
rm ticketHistory/create.php; mv ticketHistory/create.php.new ticketHistory/create.php
rm trnCatCodes/update.php; mv trnCatCodes/update.php.new trnCatCodes/update.php
rm trnCatCodes/view.php; mv trnCatCodes/view.php.new trnCatCodes/view.php
rm trnCatCodes/admin.php; mv trnCatCodes/admin.php.new trnCatCodes/admin.php
rm trnCatCodes/index.php; mv trnCatCodes/index.php.new trnCatCodes/index.php
rm trnCatCodes/create.php; mv trnCatCodes/create.php.new trnCatCodes/create.php
rm reminders/update.php; mv reminders/update.php.new reminders/update.php
rm reminders/view.php; mv reminders/view.php.new reminders/view.php
rm reminders/admin.php; mv reminders/admin.php.new reminders/admin.php
rm reminders/index.php; mv reminders/index.php.new reminders/index.php
rm reminders/create.php; mv reminders/create.php.new reminders/create.php
rm transactions/update.php; mv transactions/update.php.new transactions/update.php
rm transactions/view.php; mv transactions/view.php.new transactions/view.php
rm transactions/admin.php; mv transactions/admin.php.new transactions/admin.php
rm transactions/index.php; mv transactions/index.php.new transactions/index.php
rm transactions/create.php; mv transactions/create.php.new transactions/create.php
rm help/index.php; mv help/index.php.new help/index.php
rm tickets/update.php; mv tickets/update.php.new tickets/update.php
rm tickets/view.php; mv tickets/view.php.new tickets/view.php
rm tickets/admin.php; mv tickets/admin.php.new tickets/admin.php
rm tickets/index.php; mv tickets/index.php.new tickets/index.php
rm tickets/create.php; mv tickets/create.php.new tickets/create.php
rm accounts/update.php; mv accounts/update.php.new accounts/update.php
rm accounts/view.php; mv accounts/view.php.new accounts/view.php
rm accounts/admin.php; mv accounts/admin.php.new accounts/admin.php
rm accounts/index.php; mv accounts/index.php.new accounts/index.php
rm accounts/create.php; mv accounts/create.php.new accounts/create.php
rm registries/update.php; mv registries/update.php.new registries/update.php
rm registries/view.php; mv registries/view.php.new registries/view.php
rm registries/admin.php; mv registries/admin.php.new registries/admin.php
rm registries/index.php; mv registries/index.php.new registries/index.php
rm registries/create.php; mv registries/create.php.new registries/create.php
rm lobby/view.php; mv lobby/view.php.new lobby/view.php
rm posts/update.php; mv posts/update.php.new posts/update.php
rm posts/admin.php; mv posts/admin.php.new posts/admin.php
rm posts/index.php; mv posts/index.php.new posts/index.php
rm posts/create.php; mv posts/create.php.new posts/create.php
rm trnCat/update.php; mv trnCat/update.php.new trnCat/update.php
rm trnCat/view.php; mv trnCat/view.php.new trnCat/view.php
rm trnCat/admin.php; mv trnCat/admin.php.new trnCat/admin.php
rm trnCat/index.php; mv trnCat/index.php.new trnCat/index.php
rm trnCat/create.php; mv trnCat/create.php.new trnCat/create.php
rm forums/update.php; mv forums/update.php.new forums/update.php
rm forums/view.php; mv forums/view.php.new forums/view.php
rm forums/admin.php; mv forums/admin.php.new forums/admin.php
rm forums/index.php; mv forums/index.php.new forums/index.php
rm forums/create.php; mv forums/create.php.new forums/create.php
rm polls/update.php; mv polls/update.php.new polls/update.php
rm polls/view.php; mv polls/view.php.new polls/view.php
rm polls/admin.php; mv polls/admin.php.new polls/admin.php
rm polls/index.php; mv polls/index.php.new polls/index.php
rm polls/create.php; mv polls/create.php.new polls/create.php
rm ads/update.php; mv ads/update.php.new ads/update.php
rm ads/view.php; mv ads/view.php.new ads/view.php
rm ads/admin.php; mv ads/admin.php.new ads/admin.php
rm ads/index.php; mv ads/index.php.new ads/index.php
rm ads/create.php; mv ads/create.php.new ads/create.php
rm projects/update.php; mv projects/update.php.new projects/update.php
rm projects/admin.php; mv projects/admin.php.new projects/admin.php
rm projects/index.php; mv projects/index.php.new projects/index.php
rm projects/create.php; mv projects/create.php.new projects/create.php
rm contactCodes/update.php; mv contactCodes/update.php.new contactCodes/update.php
rm contactCodes/view.php; mv contactCodes/view.php.new contactCodes/view.php
rm contactCodes/admin.php; mv contactCodes/admin.php.new contactCodes/admin.php
rm contactCodes/index.php; mv contactCodes/index.php.new contactCodes/index.php
rm contactCodes/create.php; mv contactCodes/create.php.new contactCodes/create.php
rm aptMaintenance/update.php; mv aptMaintenance/update.php.new aptMaintenance/update.php
rm aptMaintenance/view.php; mv aptMaintenance/view.php.new aptMaintenance/view.php
rm aptMaintenance/admin.php; mv aptMaintenance/admin.php.new aptMaintenance/admin.php
rm aptMaintenance/index.php; mv aptMaintenance/index.php.new aptMaintenance/index.php
rm aptMaintenance/create.php; mv aptMaintenance/create.php.new aptMaintenance/create.php
rm tenants/update.php; mv tenants/update.php.new tenants/update.php
rm tenants/view.php; mv tenants/view.php.new tenants/view.php
rm tenants/admin.php; mv tenants/admin.php.new tenants/admin.php
rm tenants/index.php; mv tenants/index.php.new tenants/index.php
rm tenants/create.php; mv tenants/create.php.new tenants/create.php
rm comments/update.php; mv comments/update.php.new comments/update.php
rm comments/view.php; mv comments/view.php.new comments/view.php
rm comments/admin.php; mv comments/admin.php.new comments/admin.php
rm comments/index.php; mv comments/index.php.new comments/index.php
rm comments/create.php; mv comments/create.php.new comments/create.php
rm appartments/update.php; mv appartments/update.php.new appartments/update.php
rm appartments/view.php; mv appartments/view.php.new appartments/view.php
rm appartments/admin.php; mv appartments/admin.php.new appartments/admin.php
rm appartments/index.php; mv appartments/index.php.new appartments/index.php
rm appartments/create.php; mv appartments/create.php.new appartments/create.php
rm contacts/update.php; mv contacts/update.php.new contacts/update.php
rm contacts/view.php; mv contacts/view.php.new contacts/view.php
rm contacts/admin.php; mv contacts/admin.php.new contacts/admin.php
rm contacts/index.php; mv contacts/index.php.new contacts/index.php
rm contacts/create.php; mv contacts/create.php.new contacts/create.php
rm adCatCodes/update.php; mv adCatCodes/update.php.new adCatCodes/update.php
rm adCatCodes/view.php; mv adCatCodes/view.php.new adCatCodes/view.php
rm adCatCodes/admin.php; mv adCatCodes/admin.php.new adCatCodes/admin.php
rm adCatCodes/index.php; mv adCatCodes/index.php.new adCatCodes/index.php
rm adCatCodes/create.php; mv adCatCodes/create.php.new adCatCodes/create.php
rm postCodes/update.php; mv postCodes/update.php.new postCodes/update.php
rm postCodes/admin.php; mv postCodes/admin.php.new postCodes/admin.php
rm postCodes/index.php; mv postCodes/index.php.new postCodes/index.php
rm postCodes/create.php; mv postCodes/create.php.new postCodes/create.php
rm admin/index.php; mv admin/index.php.new admin/index.php
