#!/usr/bin/perl

my @files = (
'incomes/update.php',
'incomes/view.php',
'incomes/admin.php',
'incomes/index.php',
'incomes/create.php',
'site/contact.php',
'site/pages/about.php',
'site/login.php',
'site/index.php',
'pollCodes/update.php',
'pollCodes/view.php',
'pollCodes/admin.php',
'pollCodes/index.php',
'pollCodes/create.php',
'ticketCodes/update.php',
'ticketCodes/view.php',
'ticketCodes/admin.php',
'ticketCodes/index.php',
'ticketCodes/create.php',
'sites/update.php',
'sites/view.php',
'sites/admin.php',
'sites/index.php',
'sites/create.php',
'bankCodes/update.php',
'bankCodes/view.php',
'bankCodes/admin.php',
'bankCodes/index.php',
'bankCodes/create.php',
'commentCodes/update.php',
'commentCodes/view.php',
'commentCodes/admin.php',
'commentCodes/index.php',
'commentCodes/create.php',
'buildings/update.php',
'buildings/view.php',
'buildings/admin.php',
'buildings/index.php',
'buildings/create.php',
'ticketHistory/update.php',
'ticketHistory/view.php',
'ticketHistory/admin.php',
'ticketHistory/index.php',
'ticketHistory/create.php',
'trnCatCodes/update.php',
'trnCatCodes/view.php',
'trnCatCodes/admin.php',
'trnCatCodes/index.php',
'trnCatCodes/create.php',
'reminders/update.php',
'reminders/view.php',
'reminders/admin.php',
'reminders/index.php',
'reminders/create.php',
'transactions/update.php',
'transactions/view.php',
'transactions/admin.php',
'transactions/index.php',
'transactions/create.php',
'help/index.php',
'tickets/update.php',
'tickets/view.php',
'tickets/admin.php',
'tickets/index.php',
'tickets/create.php',
'accounts/update.php',
'accounts/view.php',
'accounts/admin.php',
'accounts/index.php',
'accounts/create.php',
'registries/update.php',
'registries/view.php',
'registries/admin.php',
'registries/index.php',
'registries/create.php',
'lobby/view.php',
'posts/update.php',
'posts/admin.php',
'posts/index.php',
'posts/create.php',
'trnCat/update.php',
'trnCat/view.php',
'trnCat/admin.php',
'trnCat/index.php',
'trnCat/create.php',
'forums/update.php',
'forums/view.php',
'forums/admin.php',
'forums/index.php',
'forums/create.php',
'polls/update.php',
'polls/view.php',
'polls/admin.php',
'polls/index.php',
'polls/create.php',
'ads/update.php',
'ads/view.php',
'ads/admin.php',
'ads/index.php',
'ads/create.php',
'projects/update.php',
'projects/admin.php',
'projects/index.php',
'projects/create.php',
'contactCodes/update.php',
'contactCodes/view.php',
'contactCodes/admin.php',
'contactCodes/index.php',
'contactCodes/create.php',
'aptMaintenance/update.php',
'aptMaintenance/view.php',
'aptMaintenance/admin.php',
'aptMaintenance/index.php',
'aptMaintenance/create.php',
'tenants/update.php',
'tenants/view.php',
'tenants/admin.php',
'tenants/index.php',
'tenants/create.php',
'comments/update.php',
'comments/view.php',
'comments/admin.php',
'comments/index.php',
'comments/create.php',
'appartments/update.php',
'appartments/view.php',
'appartments/admin.php',
'appartments/index.php',
'appartments/create.php',
'contacts/update.php',
'contacts/view.php',
'contacts/admin.php',
'contacts/index.php',
'contacts/create.php',
'adCatCodes/update.php',
'adCatCodes/view.php',
'adCatCodes/admin.php',
'adCatCodes/index.php',
'adCatCodes/create.php',
'postCodes/update.php',
'postCodes/admin.php',
'postCodes/index.php',
'postCodes/create.php',
'admin/index.php',
);


foreach my $file (@files) {
	# print "$file\n";
	open INP , "<$file" or die($file);
	open OUT, ">$file.new" or die;
	while (my $line = <INP>) {
		my $rem = 0;
		if ($line =~ /'app', 'List'/) { $rem = 1;};
		if ($line =~ /'app', 'Create'/) { $rem = 1;};
		if ($line =~ /'app', 'Manage'/) { $rem = 1;};
		if ($line =~ /'app', 'Update'/) { $rem = 1;};
		if ($line =~ /'app', 'Delete'/) { $rem = 1;};
		if ($rem && ($line !~ /'label'/)) { $rem = 0; }
		if ($rem) {
			$line =~ s/\)[^u]*/),'/;
		}
		print OUT $line ;
	}
	close INP;
	close OUT;
	print "rm $file; mv $file.new $file\n";
}

