<?php

/**
 * This is the model base class for the table "poll_attendents".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PollAttendents".
 *
 * Columns in table "poll_attendents" available as properties of the model,
 * followed by relations of table "poll_attendents" available as properties of the model.
 *
 * @property integer $pol_id
 * @property integer $bld_id
 * @property integer $tnt_id
 * @property integer $app_num
 * @property integer $option_selected
 *
 * @property PollOptions $optionSelected
 * @property Polls $pol
 * @property Tenants $tnt
 */
abstract class BasePollAttendents extends VdActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'poll_attendents';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PollAttendents|PollAttendents', $n);
	}

	public static function representingColumn() {
		return array(
			'pol_id',
			'bld_id',
			'tnt_id',
		);
	}

	public function rules() {
		return array(
			array('pol_id,  tnt_id, app_num', 'required'),
			array('pol_id, bld_id, tnt_id, app_num, option_selected', 'numerical', 'integerOnly'=>true),
			array('option_selected', 'default', 'setOnEmpty' => true, 'value' => null),
			array('pol_id, bld_id, tnt_id, app_num, option_selected', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'optionSelected' => array(self::BELONGS_TO, 'PollOptions', 'option_selected'),
			'pol' => array(self::BELONGS_TO, 'Polls', 'pol_id'),
			'tnt' => array(self::BELONGS_TO, 'Tenants', 'tnt_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'pol_id' => null,
			'bld_id' => Yii::t('app', 'Bld'),
			'tnt_id' => null,
			'app_num' => Yii::t('app', 'App Num'),
			'option_selected' => null,
			'optionSelected' => null,
			'pol' => null,
			'tnt' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('pol_id', $this->pol_id);
		$criteria->compare('bld_id', $this->bld_id);
		$criteria->compare('tnt_id', $this->tnt_id);
		$criteria->compare('app_num', $this->app_num);
		$criteria->compare('option_selected', $this->option_selected);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
