<?php

/**
 * This is the model base class for the table "transactions".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Transactions".
 *
 * Columns in table "transactions" available as properties of the model,
 * followed by relations of table "transactions" available as properties of the model.
 *
 * @property integer $id
 * @property integer $bld_id
 * @property integer $acc_id
 * @property integer $prj_id
 * @property string $trn_date
 * @property double $trn_amount
 * @property integer $trn_debit
 * @property string $trn_reference
 * @property string $trn_desc
 * @property integer $trn_cat
 *
 * @property Accounts $acc
 * @property Buildings $bld
 * @property Projects $prj
 * @property TrnCatCodes $trnCat
 */
abstract class BaseTransactions extends VdActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function getCalcAmount() {
        return $this->trn_debit * $this->trn_amount;
    }

    public function tableName() {
        return 'transactions';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Transactions|Transactions', $n);
    }

    public static function representingColumn() {
        return array('trn_desc', 'trn_date', 'trn_amount');
    }

    public function rules() {
        return array(
            array('acc_id, prj_id, trn_date, trn_amount', 'required'),
            array(' acc_id, prj_id, trn_debit, trn_cat', 'numerical', 'integerOnly' => true),
            array('trn_amount', 'numerical'),
            array('trn_reference', 'length', 'max' => 30),
            array('trn_desc', 'length', 'max' => 255),
            array('trn_debit, trn_reference, trn_desc, trn_cat', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, acc_id, prj_id, trn_date, trn_amount, trn_debit, trn_reference, trn_desc, trn_cat', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'acc' => array(self::BELONGS_TO, 'Accounts', 'acc_id'),
            'bld' => array(self::BELONGS_TO, 'Buildings', 'bld_id'),
            'prj' => array(self::BELONGS_TO, 'Projects', 'prj_id'),
            'trnCat' => array(self::BELONGS_TO, 'TrnCatCodes', 'trn_cat'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'bld_id' => null,
            'acc_id' => null,
            'prj_id' => null,
            'trn_date' => Yii::t('app', 'Trn Date'),
            'trn_amount' => Yii::t('app', 'Trn Amount'),
            'trn_debit' => Yii::t('app', 'Trn Debit'),
            'trn_reference' => Yii::t('app', 'Trn Reference'),
            'trn_desc' => Yii::t('app', 'Trn Desc'),
            'trn_cat' => null,
            'acc' => null,
            'bld' => null,
            'prj' => null,
            'trnCat' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('bld_id', $this->bld_id);
        $criteria->compare('acc_id', $this->acc_id);
        $criteria->compare('prj_id', $this->prj_id);
        $criteria->compare('trn_date', $this->trn_date, true);
        $criteria->compare('trn_amount', $this->trn_amount);
        $criteria->compare('trn_debit', $this->trn_debit);
        $criteria->compare('trn_reference', $this->trn_reference, true);
        $criteria->compare('trn_desc', $this->trn_desc, true);
        $criteria->compare('trn_cat', $this->trn_cat);

        return new CActiveDataProvider($this, array(
                    'criteria' => $criteria,
                ));
    }

}