<?php

/**
 * This is the model base class for the table "comments".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Comments".
 *
 * Columns in table "comments" available as properties of the model,
 * followed by relations of table "comments" available as properties of the model.
 *
 * @property integer $id
 * @property integer $bld_id
 * @property integer $post_id
 * @property integer $author_id
 * @property string $content_text
 * @property integer $status
 * @property string $create_time
 * @property boolean $is_locked
 *
 * @property Tenants $author
 * @property Buildings $bld
 * @property Posts $post
 * @property CommentCodes $status0
 */
abstract class BaseComments extends VdActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comments';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Comments|Comments', $n);
	}

	public static function representingColumn() {
		return 'content_text';
	}

	public function rules() {
		return array(
			array(' post_id, author_id, content_text, status', 'required'),
			array('bld_id, post_id, author_id, status', 'numerical', 'integerOnly'=>true),
			array('create_time, is_locked', 'safe'),
			array('create_time, is_locked', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, bld_id, post_id, author_id, content_text, status, create_time, is_locked', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'author' => array(self::BELONGS_TO, 'Tenants', 'author_id'),
			'bld' => array(self::BELONGS_TO, 'Buildings', 'bld_id'),
			'post' => array(self::BELONGS_TO, 'Posts', 'post_id'),
			'status0' => array(self::BELONGS_TO, 'CommentCodes', 'status'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'bld_id' => null,
			'post_id' => null,
			'author_id' => null,
			'content_text' => Yii::t('app', 'Content Text'),
			'status' => null,
			'create_time' => Yii::t('app', 'Create Time'),
			'is_locked' => Yii::t('app', 'Is Locked'),
			'author' => null,
			'bld' => null,
			'post' => null,
			'status0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('bld_id', $this->bld_id);
		$criteria->compare('post_id', $this->post_id);
		$criteria->compare('author_id', $this->author_id);
		$criteria->compare('content_text', $this->content_text, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('is_locked', $this->is_locked);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
