<?php

/**
 * This is the model base class for the table "contacts".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Contacts".
 *
 * Columns in table "contacts" available as properties of the model,
 * followed by relations of table "contacts" available as properties of the model.
 *
 * @property integer $id
 * @property integer $bld_id
 * @property string $cnt_first_name
 * @property string $cnt_last_name
 * @property string $cnt_phone1
 * @property string $cnt_phone2
 * @property string $cnt_address
 * @property string $cnt_remarks
 * @property integer $cnt_type
 * @property string $cnt_email
 *
 * @property Buildings $bld
 * @property ContactCodes $cntType
 */
abstract class BaseContacts extends VdActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'contacts';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Contacts|Contacts', $n);
	}

	public static function representingColumn() {
		return array('cnt_first_name', 'cnt_last_name');
	}

	public function rules() {
		return array(
			array('cnt_type', 'numerical', 'integerOnly'=>true),
			array('cnt_first_name, cnt_last_name, cnt_phone1, cnt_phone2', 'length', 'max'=>20),
			array('cnt_address', 'length', 'max'=>100),
			array('cnt_email', 'email'),
			array('cnt_remarks', 'safe'),
			array('cnt_first_name, cnt_last_name, cnt_phone1, cnt_phone2, cnt_address, cnt_remarks, cnt_type, cnt_email', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, bld_id, cnt_first_name, cnt_last_name, cnt_phone1, cnt_phone2, cnt_address, cnt_remarks, cnt_type, cnt_email', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'bld' => array(self::BELONGS_TO, 'Buildings', 'bld_id'),
			'cntType' => array(self::BELONGS_TO, 'ContactCodes', 'cnt_type'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'bld_id' => null,
			'cnt_first_name' => Yii::t('app', 'Cnt First Name'),
			'cnt_last_name' => Yii::t('app', 'Cnt Last Name'),
			'cnt_phone1' => Yii::t('app', 'Cnt Phone1'),
			'cnt_phone2' => Yii::t('app', 'Cnt Phone2'),
			'cnt_address' => Yii::t('app', 'Cnt Address'),
			'cnt_remarks' => Yii::t('app', 'Cnt Remarks'),
			'cnt_type' => null,
			'cnt_email' => Yii::t('app', 'Cnt Email'),
			'bld' => null,
			'cntType' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('bld_id', $this->bld_id);
		$criteria->compare('cnt_first_name', $this->cnt_first_name, true);
		$criteria->compare('cnt_last_name', $this->cnt_last_name, true);
		$criteria->compare('cnt_phone1', $this->cnt_phone1, true);
		$criteria->compare('cnt_phone2', $this->cnt_phone2, true);
		$criteria->compare('cnt_address', $this->cnt_address, true);
		$criteria->compare('cnt_remarks', $this->cnt_remarks, true);
		$criteria->compare('cnt_type', $this->cnt_type);
		$criteria->compare('cnt_email', $this->cnt_email, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}