<?php

/**
 * This is the model base class for the table "tags".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tags".
 *
 * Columns in table "tags" available as properties of the model,
 * followed by relations of table "tags" available as properties of the model.
 *
 * @property integer $id
 * @property integer $bld_id
 * @property string $tag_name
 * @property integer $frequency
 *
 * @property Buildings $bld
 * @property PostTags[] $postTags
 */
abstract class BaseTags extends VdActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tags';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tags|Tags', $n);
	}

	public static function representingColumn() {
		return 'tag_name';
	}

	public function rules() {
		return array(
			array(' tag_name', 'required'),
			array('bld_id, frequency', 'numerical', 'integerOnly'=>true),
			array('tag_name', 'length', 'max'=>128),
			array('frequency', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, bld_id, tag_name, frequency', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'bld' => array(self::BELONGS_TO, 'Buildings', 'bld_id'),
			'postTags' => array(self::HAS_MANY, 'PostTags', 'tag_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'bld_id' => null,
			'tag_name' => Yii::t('app', 'Tag Name'),
			'frequency' => Yii::t('app', 'Frequency'),
			'bld' => null,
			'postTags' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('bld_id', $this->bld_id);
		$criteria->compare('tag_name', $this->tag_name, true);
		$criteria->compare('frequency', $this->frequency);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
