<?php

/**
 * This is the model base class for the table "apt_maintenance".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AptMaintenance".
 *
 * Columns in table "apt_maintenance" available as properties of the model,
 * followed by relations of table "apt_maintenance" available as properties of the model.
 *
 * @property integer $id
 * @property integer $bld_id
 * @property integer $apt_id
 * @property string $start_date
 * @property double $amount
 *
 * @property Appartments $apt
 * @property Buildings $bld
 */
abstract class BaseAptMaintenance extends VdActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'apt_maintenance';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AptMaintenance|AptMaintenances', $n);
	}

	public static function representingColumn() {
		return 'start_date';
	}

	public function rules() {
		return array(
			array('apt_id, start_date', 'required'),
			array('bld_id, apt_id', 'numerical', 'integerOnly'=>true),
			array('amount', 'numerical'),
			array('amount', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, bld_id, apt_id, start_date, amount', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'apt' => array(self::BELONGS_TO, 'Appartments', 'apt_id'),
			'bld' => array(self::BELONGS_TO, 'Buildings', 'bld_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'bld_id' => null,
			'apt_id' => null,
			'start_date' => Yii::t('app', 'Start Date'),
			'amount' => Yii::t('app', 'Amount'),
			'apt' => null,
			'bld' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('bld_id', $this->bld_id);
		$criteria->compare('apt_id', $this->apt_id);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('amount', $this->amount);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
