<?php

/**
 * This is the model base class for the table "v_trans".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VTrans".
 *
 * Columns in table "v_trans" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $bld_id
 * @property integer $acc_id
 * @property integer $prj_id
 * @property string $trn_date
 * @property double $trn_amount
 * @property integer $trn_debit
 * @property string $trn_reference
 * @property string $trn_desc
 * @property integer $trn_cat
 * @property double $mm
 * @property double $yy
 *
 */
abstract class BaseVTrans extends GxActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'v_trans';
    }

    public function primaryKey() {
        return 'id';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'VTran|VTrans', $n);
    }

    public static function representingColumn() {
        return 'trn_date';
    }

    public function rules() {
        return array(
            array('id, bld_id, acc_id, prj_id, trn_debit, trn_cat', 'numerical', 'integerOnly' => true),
            array('trn_amount, mm, yy', 'numerical'),
            array('trn_reference', 'length', 'max' => 30),
            array('trn_desc', 'length', 'max' => 255),
            array('trn_date', 'safe'),
            array('id, bld_id, acc_id, prj_id, trn_date, trn_amount, trn_debit, trn_reference, trn_desc, trn_cat, mm, yy', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, bld_id, acc_id, prj_id, trn_date, trn_amount, trn_debit, trn_reference, trn_desc, trn_cat, mm, yy', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'acc' => array(self::BELONGS_TO, 'Accounts', 'acc_id'),
            'bld' => array(self::BELONGS_TO, 'Buildings', 'bld_id'),
            'prj' => array(self::BELONGS_TO, 'Projects', 'prj_id'),
            'trnCat' => array(self::BELONGS_TO, 'TrnCatCodes', 'trn_cat'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'bld_id' => Yii::t('app', 'Bld'),
            'acc_id' => Yii::t('app', 'Acc'),
            'prj_id' => Yii::t('app', 'Prj'),
            'trn_date' => Yii::t('app', 'Trn Date'),
            'trn_amount' => Yii::t('app', 'Trn Amount'),
            'trn_debit' => Yii::t('app', 'Trn Debit'),
            'trn_reference' => Yii::t('app', 'Trn Reference'),
            'trn_desc' => Yii::t('app', 'Trn Desc'),
            'trn_cat' => Yii::t('app', 'Trn Cat'),
            'mm' => Yii::t('app', 'Mm'),
            'yy' => Yii::t('app', 'Yy'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;



        $criteria->select = 'yy'
                . ', SUM(trn_amount) as trn_amount';
        $criteria->group = 'yy';
        $criteria->order = 'yy Asc';

        $criteria->compare('bld_id', $this->bld_id);
        $criteria->compare('prj_id', $this->prj_id);

        var_dump($criteria);
        return new CActiveDataProvider($this, array(
                    'criteria' => $criteria,
                ));
    }

}