<?php

/**
 * This is the model base class for the table "receipts".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Receipts".
 *
 * Columns in table "receipts" available as properties of the model,
 * followed by relations of table "receipts" available as properties of the model.
 *
 * @property integer $id
 * @property integer $bld_id
 * @property integer $ser_num
 * @property integer $rct_year
 * @property string $rct_date
 * @property double $rct_amount
 * @property integer $rct_tnt_id
 * @property string $rct_name
 * @property string $rct_full_address
 * @property string $rct_city
 * @property string $rct_zip
 * @property string $rct_phone
 * @property integer $rct_trn_id
 *
 * @property Buildings $bld
 */
abstract class BaseReceipts extends VdActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'receipts';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Receipts|Receipts', $n);
	}

	public static function representingColumn() {
		return 'rct_date';
	}

	public function rules() {
		return array(
			array(' ser_num, rct_date, rct_amount', 'required'),
			array('bld_id, ser_num, rct_year, rct_tnt_id, rct_trn_id', 'numerical', 'integerOnly'=>true),
			array('rct_amount', 'numerical'),
			array('rct_name, rct_city', 'length', 'max'=>60),
			array('rct_full_address', 'length', 'max'=>250),
			array('rct_zip', 'length', 'max'=>10),
			array('rct_phone', 'length', 'max'=>15),
			array('rct_year, rct_tnt_id, rct_name, rct_full_address, rct_city, rct_zip, rct_phone, rct_trn_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, bld_id, ser_num, rct_year, rct_date, rct_amount, rct_tnt_id, rct_name, rct_full_address, rct_city, rct_zip, rct_phone, rct_trn_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'bld' => array(self::BELONGS_TO, 'Buildings', 'bld_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'bld_id' => null,
			'ser_num' => Yii::t('app', 'Ser Num'),
			'rct_year' => Yii::t('app', 'Rct Year'),
			'rct_date' => Yii::t('app', 'Rct Date'),
			'rct_amount' => Yii::t('app', 'Rct Amount'),
			'rct_tnt_id' => Yii::t('app', 'Rct Tnt'),
			'rct_name' => Yii::t('app', 'Rct Name'),
			'rct_full_address' => Yii::t('app', 'Rct Full Address'),
			'rct_city' => Yii::t('app', 'Rct City'),
			'rct_zip' => Yii::t('app', 'Rct Zip'),
			'rct_phone' => Yii::t('app', 'Rct Phone'),
			'rct_trn_id' => Yii::t('app', 'Rct Trn'),
			'bld' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('bld_id', $this->bld_id);
		$criteria->compare('ser_num', $this->ser_num);
		$criteria->compare('rct_year', $this->rct_year);
		$criteria->compare('rct_date', $this->rct_date, true);
		$criteria->compare('rct_amount', $this->rct_amount);
		$criteria->compare('rct_tnt_id', $this->rct_tnt_id);
		$criteria->compare('rct_name', $this->rct_name, true);
		$criteria->compare('rct_full_address', $this->rct_full_address, true);
		$criteria->compare('rct_city', $this->rct_city, true);
		$criteria->compare('rct_zip', $this->rct_zip, true);
		$criteria->compare('rct_phone', $this->rct_phone, true);
		$criteria->compare('rct_trn_id', $this->rct_trn_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
