<?php

/**
 * This is the model base class for the table "bank_codes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BankCodes".
 *
 * Columns in table "bank_codes" available as properties of the model,
 * followed by relations of table "bank_codes" available as properties of the model.
 *
 * @property integer $id
 * @property string $code_desc
 *
 * @property Accounts[] $accounts
 * @property Incomes[] $incomes
 */
abstract class BaseBankCodes extends GxActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    protected function beforeFind() {
        $criteria = new CDbCriteria;
        $criteria->order = "id ASC";
        $this->dbCriteria->mergeWith($criteria);
        parent::beforeFind();
    }

    public function tableName() {
        return 'bank_codes';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'BankCodes|BankCodes', $n);
    }

    public static function representingColumn() {
        return 'code_desc';
    }

    public function rules() {
        return array(
            array('code_desc', 'length', 'max' => 30),
            array('code_desc', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, code_desc', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'accounts' => array(self::HAS_MANY, 'Accounts', 'acc_bank'),
            'incomes' => array(self::HAS_MANY, 'Incomes', 'inc_bank'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'code_desc' => Yii::t('app', 'Code Desc'),
            'accounts' => null,
            'incomes' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('code_desc', $this->code_desc, true);

        return new CActiveDataProvider($this, array(
                    'criteria' => $criteria,
                ));
    }

}