<?php

/**
 * This is the model base class for the table "app_taxes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AppTaxes".
 *
 * Columns in table "app_taxes" available as properties of the model,
 * followed by relations of table "app_taxes" available as properties of the model.
 *
 * @property integer $app_id
 * @property integer $bld_id
 * @property string $start_date
 * @property integer $app_num
 * @property double $tax_amount
 *
 * @property Appartments $app
 * @property Buildings $bld
 */
abstract class BaseAppTaxes extends VdActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'app_taxes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AppTaxes|AppTaxes', $n);
	}

	public static function representingColumn() {
		return 'start_date';
	}

	public function rules() {
		return array(
			array('app_id, start_date, app_num', 'required'),
			array('app_id, bld_id, app_num', 'numerical', 'integerOnly'=>true),
			array('tax_amount', 'numerical'),
			array('tax_amount', 'default', 'setOnEmpty' => true, 'value' => null),
			array('app_id, bld_id, start_date, app_num, tax_amount', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'app' => array(self::BELONGS_TO, 'Appartments', 'app_id'),
			'bld' => array(self::BELONGS_TO, 'Buildings', 'bld_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'app_id' => null,
			'bld_id' => null,
			'start_date' => Yii::t('app', 'Start Date'),
			'app_num' => Yii::t('app', 'App Num'),
			'tax_amount' => Yii::t('app', 'Tax Amount'),
			'app' => null,
			'bld' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('app_id', $this->app_id);
		$criteria->compare('bld_id', $this->bld_id);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('app_num', $this->app_num);
		$criteria->compare('tax_amount', $this->tax_amount);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
