<?php

/**
 * This is the model base class for the table "tenants".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tenants".
 *
 * Columns in table "tenants" available as properties of the model,
 * followed by relations of table "tenants" available as properties of the model.
 *
 * @property integer $id
 * @property integer $bld_id
 * @property boolean $tnt_is_active
 * @property integer $tnt_app_num
 * @property string $tnt_first_name
 * @property string $tnt_last_name
 * @property string $tnt_password
 * @property string $tnt_birthday
 * @property string $tnt_email
 * @property string $tnt_app_phone
 * @property string $tnt_picture
 * @property string $tnt_mobile
 * @property string $tnt_entry_date
 * @property double $tnt_prev_debt
 * @property string $tnt_occupation
 * @property boolean $tnt_is_vaad
 * @property boolean $tnt_is_owner
 * @property boolean $tnt_is_site_vaad
 * @property boolean $tnt_is_nbrhd_vaad
 * @property boolean $tnt_is_city_vaad
 * @property boolean $tnt_is_admin
 *
 * @property Buildings $bld
 * @property Appartments $tntAppNum
 * @property Comments[] $comments
 * @property Tasks[] $tasks
 * @property TicketHistory[] $ticketHistories
 * @property Tickets[] $tickets
 * @property Forums[] $forums
 * @property PollAttendents[] $pollAttendents
 * @property Posts[] $posts
 */
abstract class BaseTenants extends VdActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    protected function beforeFind() {
        $criteria = new CDbCriteria;
        $criteria->order = "tnt_app_num ASC";
        $this->dbCriteria->mergeWith($criteria);
        parent::beforeFind();
    }

    public function tableName() {
        return 'tenants';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Tenant|Tenants', $n);
    }

    public static function representingColumn() {
        return array('tnt_first_name', 'tnt_last_name');
    }

    public function rules() {
        return array(
            array('tnt_app_num, tnt_first_name, tnt_last_name', 'required'),
            array('tnt_app_num', 'numerical', 'integerOnly' => true),
            array('tnt_prev_debt', 'numerical'),
            array('tnt_first_name, tnt_last_name', 'length', 'max' => 15),
            array('tnt_password, tnt_email', 'length', 'max' => 60),
            array('tnt_app_phone, tnt_mobile', 'length', 'max' => 20),
            array('tnt_picture', 'length', 'max' => 255),
            array('tnt_occupation', 'length', 'max' => 30),
            array('tnt_is_active, tnt_birthday, tnt_entry_date, tnt_is_vaad, tnt_is_owner, tnt_is_site_vaad, tnt_is_nbrhd_vaad, tnt_is_city_vaad, tnt_is_admin', 'safe'),
            array('tnt_is_active, tnt_password, tnt_birthday, tnt_email, tnt_app_phone, tnt_picture, tnt_mobile, tnt_entry_date, tnt_prev_debt, tnt_occupation, tnt_is_vaad, tnt_is_owner, tnt_is_site_vaad, tnt_is_nbrhd_vaad, tnt_is_city_vaad, tnt_is_admin', 'default', 'setOnEmpty' => true, 'value' => null),
            array('tnt_is_active, tnt_app_num, tnt_first_name, tnt_last_name, tnt_password, tnt_birthday, tnt_email, tnt_app_phone, tnt_picture, tnt_mobile, tnt_entry_date, tnt_prev_debt, tnt_occupation, tnt_is_vaad, tnt_is_owner, tnt_is_site_vaad, tnt_is_nbrhd_vaad, tnt_is_city_vaad, tnt_is_admin', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'bld' => array(self::BELONGS_TO, 'Buildings', 'bld_id'),
            'tntAppNum' => array(self::BELONGS_TO, 'Appartments', 'tnt_app_num'),
            'comments' => array(self::HAS_MANY, 'Comments', 'author_id'),
            'tasks' => array(self::HAS_MANY, 'Tasks', 'tnt_id'),
            'ticketHistories' => array(self::HAS_MANY, 'TicketHistory', 'tnt_id'),
            'tickets' => array(self::HAS_MANY, 'Tickets', 'tnt_id'),
            'forums' => array(self::HAS_MANY, 'Forums', 'forum_mngr'),
            'pollAttendents' => array(self::HAS_MANY, 'PollAttendents', 'tnt_id'),
            'posts' => array(self::HAS_MANY, 'Posts', 'author_id'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'bld_id' => null,
            'tnt_is_active' => Yii::t('app', 'Tnt Is Active'),
            'tnt_app_num' => null,
            'tnt_first_name' => Yii::t('app', 'Tnt First Name'),
            'tnt_last_name' => Yii::t('app', 'Tnt Last Name'),
            'tnt_password' => Yii::t('app', 'Tnt Password'),
            'tnt_birthday' => Yii::t('app', 'Tnt Birthday'),
            'tnt_email' => Yii::t('app', 'Tnt Email'),
            'tnt_app_phone' => Yii::t('app', 'Tnt App Phone'),
            'tnt_picture' => Yii::t('app', 'Tnt Picture'),
            'tnt_mobile' => Yii::t('app', 'Tnt Mobile'),
            'tnt_entry_date' => Yii::t('app', 'Tnt Entry Date'),
            'tnt_prev_debt' => Yii::t('app', 'Tnt Prev Debt'),
            'tnt_occupation' => Yii::t('app', 'Tnt Occupation'),
            'tnt_is_vaad' => Yii::t('app', 'Tnt Is Vaad'),
            'tnt_is_owner' => Yii::t('app', 'Tnt Is Owner'),
            'tnt_is_site_vaad' => Yii::t('app', 'Tnt Is Site Vaad'),
            'tnt_is_nbrhd_vaad' => Yii::t('app', 'Tnt Is Nbrhd Vaad'),
            'tnt_is_city_vaad' => Yii::t('app', 'Tnt Is City Vaad'),
            'tnt_is_admin' => Yii::t('app', 'Tnt Is Admin'),
            'bld' => null,
            'tntAppNum' => null,
            'comments' => null,
            'tasks' => null,
            'ticketHistories' => null,
            'tickets' => null,
            'forums' => null,
            'pollAttendents' => null,
            'posts' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('bld_id', $this->bld_id);
        $criteria->compare('tnt_is_active', $this->tnt_is_active);
        $criteria->compare('tnt_app_num', $this->tnt_app_num);
        $criteria->compare('tnt_first_name', $this->tnt_first_name, true);
        $criteria->compare('tnt_last_name', $this->tnt_last_name, true);
        $criteria->compare('tnt_password', $this->tnt_password, true);
        $criteria->compare('tnt_birthday', $this->tnt_birthday, true);
        $criteria->compare('tnt_email', $this->tnt_email, true);
        $criteria->compare('tnt_app_phone', $this->tnt_app_phone, true);
        $criteria->compare('tnt_picture', $this->tnt_picture, true);
        $criteria->compare('tnt_mobile', $this->tnt_mobile, true);
        $criteria->compare('tnt_entry_date', $this->tnt_entry_date, true);
        $criteria->compare('tnt_prev_debt', $this->tnt_prev_debt);
        $criteria->compare('tnt_occupation', $this->tnt_occupation, true);
        $criteria->compare('tnt_is_vaad', $this->tnt_is_vaad);
        $criteria->compare('tnt_is_owner', $this->tnt_is_owner);
        $criteria->compare('tnt_is_site_vaad', $this->tnt_is_site_vaad);
        $criteria->compare('tnt_is_nbrhd_vaad', $this->tnt_is_nbrhd_vaad);
        $criteria->compare('tnt_is_city_vaad', $this->tnt_is_city_vaad);
        $criteria->compare('tnt_is_admin', $this->tnt_is_admin);

        return new CActiveDataProvider($this, array(
                    'criteria' => $criteria,
                ));
    }

}