<?php

/**
 * This is the model base class for the table "accounts".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Accounts".
 *
 * Columns in table "accounts" available as properties of the model,
 * followed by relations of table "accounts" available as properties of the model.
 *
 * @property integer $id
 * @property integer $bld_id
 * @property string $acc_type
 * @property string $acc_branch
 * @property string $acc_number
 * @property double $acc_starting_amount
 * @property string $acc_remarks
 * @property integer $acc_bank
 *
 * @property BankCodes $accBank
 * @property Buildings $bld
 * @property Transactions[] $transactions
 */
abstract class BaseAccounts extends VdActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'accounts';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Accounts|Accounts', $n);
	}

	public static function representingColumn() {
		return array('acc_remarks','acc_number');
	}

	public function rules() {
		return array(
			array('bld_id, acc_bank', 'numerical', 'integerOnly'=>true),
			array('acc_starting_amount', 'numerical'),
			array('acc_type, acc_branch', 'length', 'max'=>3),
			array('acc_number', 'length', 'max'=>20),
			array('acc_remarks', 'safe'),
			array('acc_type, acc_branch, acc_number, acc_starting_amount, acc_remarks, acc_bank', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, bld_id, acc_type, acc_branch, acc_number, acc_starting_amount, acc_remarks, acc_bank', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'accBank' => array(self::BELONGS_TO, 'BankCodes', 'acc_bank'),
			'bld' => array(self::BELONGS_TO, 'Buildings', 'bld_id'),
			'transactions' => array(self::HAS_MANY, 'Transactions', 'acc_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'bld_id' => null,
			'acc_type' => Yii::t('app', 'Acc Type'),
			'acc_branch' => Yii::t('app', 'Acc Branch'),
			'acc_number' => Yii::t('app', 'Acc Number'),
			'acc_starting_amount' => Yii::t('app', 'Acc Starting Amount'),
			'acc_remarks' => Yii::t('app', 'Acc Remarks'),
			'acc_bank' => null,
			'accBank' => null,
			'bld' => null,
			'transactions' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('bld_id', $this->bld_id);
		$criteria->compare('acc_type', $this->acc_type, true);
		$criteria->compare('acc_branch', $this->acc_branch, true);
		$criteria->compare('acc_number', $this->acc_number, true);
		$criteria->compare('acc_starting_amount', $this->acc_starting_amount);
		$criteria->compare('acc_remarks', $this->acc_remarks, true);
		$criteria->compare('acc_bank', $this->acc_bank);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
