<?php

/**
 * This is the model base class for the table "polls".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Polls".
 *
 * Columns in table "polls" available as properties of the model,
 * followed by relations of table "polls" available as properties of the model.
 *
 * @property integer $id
 * @property integer $bld_id
 * @property integer $pol_type
 * @property string $pol_title
 * @property string $pol_date
 * @property string $pol_desc
 * @property string $pol_exp_date
 * @property boolean $pol_on_main
 * @property boolean $pol_active
 *
 * @property Buildings $bld
 * @property PollCodes $polType
 * @property PollAttendents[] $pollAttendents
 */
abstract class BasePolls extends VdActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'polls';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Polls|Polls', $n);
	}

	public static function representingColumn() {
		return 'pol_title';
	}

	public function rules() {
		return array(
			array(' pol_title, pol_date', 'required'),
			array('bld_id, pol_type', 'numerical', 'integerOnly'=>true),
			array('pol_title', 'length', 'max'=>255),
			array('pol_desc, pol_exp_date, pol_on_main, pol_active', 'safe'),
			array('pol_type, pol_desc, pol_exp_date, pol_on_main, pol_active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, bld_id, pol_type, pol_title, pol_date, pol_desc, pol_exp_date, pol_on_main, pol_active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'bld' => array(self::BELONGS_TO, 'Buildings', 'bld_id'),
			'polType' => array(self::BELONGS_TO, 'PollCodes', 'pol_type'),
			'pollAttendents' => array(self::HAS_MANY, 'PollAttendents', 'pol_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'bld_id' => null,
			'pol_type' => null,
			'pol_title' => Yii::t('app', 'Pol Title'),
			'pol_date' => Yii::t('app', 'Pol Date'),
			'pol_desc' => Yii::t('app', 'Pol Desc'),
			'pol_exp_date' => Yii::t('app', 'Pol Exp Date'),
			'pol_on_main' => Yii::t('app', 'Pol On Main'),
			'pol_active' => Yii::t('app', 'Pol Active'),
			'bld' => null,
			'polType' => null,
			'pollAttendents' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('bld_id', $this->bld_id);
		$criteria->compare('pol_type', $this->pol_type);
		$criteria->compare('pol_title', $this->pol_title, true);
		$criteria->compare('pol_date', $this->pol_date, true);
		$criteria->compare('pol_desc', $this->pol_desc, true);
		$criteria->compare('pol_exp_date', $this->pol_exp_date, true);
		$criteria->compare('pol_on_main', $this->pol_on_main);
		$criteria->compare('pol_active', $this->pol_active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
