<?php

/**
 * This is the model base class for the table "tickets".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tickets".
 *
 * Columns in table "tickets" available as properties of the model,
 * followed by relations of table "tickets" available as properties of the model.
 *
 * @property integer $id
 * @property integer $bld_id
 * @property integer $tnt_id
 * @property integer $tkt_status
 * @property string $tkt_opendate
 * @property string $tkt_title
 * @property string $tkt_eta
 * @property string $tkt_closedate
 *
 * @property TicketHistory[] $ticketHistories
 * @property Buildings $bld
 * @property TicketCodes $tktStatus
 * @property Tenants $tnt
 */
abstract class BaseTickets extends VdActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tickets';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tickets|Tickets', $n);
	}

	public static function representingColumn() {
		return 'tkt_title';
	}

	public function rules() {
		return array(
			array(' tnt_id, tkt_title', 'required'),
			array('bld_id, tnt_id, tkt_status', 'numerical', 'integerOnly'=>true),
			array('tkt_title', 'length', 'max'=>50),
			array('tkt_opendate, tkt_eta, tkt_closedate', 'safe'),
			array('tkt_status, tkt_opendate, tkt_eta, tkt_closedate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, bld_id, tnt_id, tkt_status, tkt_opendate, tkt_title, tkt_eta, tkt_closedate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'ticketHistories' => array(self::HAS_MANY, 'TicketHistory', 'tkt_id'),
			'bld' => array(self::BELONGS_TO, 'Buildings', 'bld_id'),
			'tktStatus' => array(self::BELONGS_TO, 'TicketCodes', 'tkt_status'),
			'tnt' => array(self::BELONGS_TO, 'Tenants', 'tnt_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'bld_id' => null,
			'tnt_id' => null,
			'tkt_status' => null,
			'tkt_opendate' => Yii::t('app', 'Tkt Opendate'),
			'tkt_title' => Yii::t('app', 'Tkt Title'),
			'tkt_eta' => Yii::t('app', 'Tkt Eta'),
			'tkt_closedate' => Yii::t('app', 'Tkt Closedate'),
			'ticketHistories' => null,
			'bld' => null,
			'tktStatus' => null,
			'tnt' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('bld_id', $this->bld_id);
		$criteria->compare('tnt_id', $this->tnt_id);
		$criteria->compare('tkt_status', $this->tkt_status);
		$criteria->compare('tkt_opendate', $this->tkt_opendate, true);
		$criteria->compare('tkt_title', $this->tkt_title, true);
		$criteria->compare('tkt_eta', $this->tkt_eta, true);
		$criteria->compare('tkt_closedate', $this->tkt_closedate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
